/*
 * MOTORS_CAR_prog.c
 *
 *  Created on: Jun 29, 2023
 *      Author: fathy
 */
#include"../../LIBRARY/errorState.h"
#include"../../LIBRARY/stdTypes.h"
#include"../../MCAL/DIO/DIO_int.h"
#include "MOTORS_CAR_priv.h"
#include "MOTORS_CAR_conf.h"
void MOTORS_CAR_voidInit(void){
	DIO_voidSetPinDirection(MOTORS_CAR_EN1_GROUP,MOTORS_CAR_EN1_PIN,DIO_u8OUTPUT);
	DIO_voidSetPinDirection(MOTORS_CAR_EN2_GROUP,MOTORS_CAR_EN2_PIN,DIO_u8OUTPUT);
	DIO_voidSetPinDirection(MOTORS_CAR_A1_GROUP,MOTORS_CAR_A1_PIN,DIO_u8OUTPUT);
	DIO_voidSetPinDirection(MOTORS_CAR_A2_GROUP,MOTORS_CAR_A2_PIN,DIO_u8OUTPUT);
	DIO_voidSetPinDirection(MOTORS_CAR_A3_GROUP,MOTORS_CAR_A3_PIN,DIO_u8OUTPUT);
	DIO_voidSetPinDirection(MOTORS_CAR_A4_GROUP,MOTORS_CAR_A4_PIN,DIO_u8OUTPUT);

	DIO_voidSetPinValue(MOTORS_CAR_EN1_GROUP,MOTORS_CAR_EN1_PIN,DIO_u8HIGH);
	DIO_voidSetPinValue(MOTORS_CAR_EN2_GROUP,MOTORS_CAR_EN2_PIN,DIO_u8HIGH);

}
void MOTORS_CAR_voidForward(void){
	/*Forward left*/
	DIO_voidSetPinValue(MOTORS_CAR_A3_GROUP,MOTORS_CAR_A3_PIN,DIO_u8HIGH);
	DIO_voidSetPinValue(MOTORS_CAR_A4_GROUP,MOTORS_CAR_A4_PIN,DIO_u8LOW);
	/* FORWARD RIGHT*/
	DIO_voidSetPinValue(MOTORS_CAR_A1_GROUP,MOTORS_CAR_A1_PIN,DIO_u8LOW);
	DIO_voidSetPinValue(MOTORS_CAR_A2_GROUP,MOTORS_CAR_A2_PIN,DIO_u8HIGH);
}
void MOTORS_CAR_voidBackward(void){
	/*BACKWARD LEFT*/
	DIO_voidSetPinValue(MOTORS_CAR_A3_GROUP,MOTORS_CAR_A3_PIN,DIO_u8LOW);
	DIO_voidSetPinValue(MOTORS_CAR_A4_GROUP,MOTORS_CAR_A4_PIN,DIO_u8HIGH);
	/*BACKWARD RIGHT*/
	DIO_voidSetPinValue(MOTORS_CAR_A1_GROUP,MOTORS_CAR_A1_PIN,DIO_u8HIGH);
	DIO_voidSetPinValue(MOTORS_CAR_A2_GROUP,MOTORS_CAR_A2_PIN,DIO_u8LOW);
}
void MOTORS_CAR_voidRight(void){
	/*BACKWARD RIGHT*/
	DIO_voidSetPinValue(MOTORS_CAR_A1_GROUP,MOTORS_CAR_A1_PIN,DIO_u8HIGH);
	DIO_voidSetPinValue(MOTORS_CAR_A2_GROUP,MOTORS_CAR_A2_PIN,DIO_u8LOW);

	/* FORWARD RIGHT*/
	DIO_voidSetPinValue(MOTORS_CAR_A1_GROUP,MOTORS_CAR_A1_PIN,DIO_u8LOW);
	DIO_voidSetPinValue(MOTORS_CAR_A2_GROUP,MOTORS_CAR_A2_PIN,DIO_u8HIGH);


}
void MOTORS_CAR_voidLeft(void){
	/*BACKWARD LEFT*/
		DIO_voidSetPinValue(MOTORS_CAR_A3_GROUP,MOTORS_CAR_A3_PIN,DIO_u8LOW);
		DIO_voidSetPinValue(MOTORS_CAR_A4_GROUP,MOTORS_CAR_A4_PIN,DIO_u8HIGH);

	/* FORWARD RIGHT*/
		DIO_voidSetPinValue(MOTORS_CAR_A1_GROUP,MOTORS_CAR_A1_PIN,DIO_u8LOW);
		DIO_voidSetPinValue(MOTORS_CAR_A2_GROUP,MOTORS_CAR_A2_PIN,DIO_u8HIGH);
}
void MOTORS_CAR_voidStop(void){
	DIO_voidSetPinValue(MOTORS_CAR_A1_GROUP,MOTORS_CAR_A1_PIN,DIO_u8LOW);
	DIO_voidSetPinValue(MOTORS_CAR_A2_GROUP,MOTORS_CAR_A2_PIN,DIO_u8LOW);
	DIO_voidSetPinValue(MOTORS_CAR_A3_GROUP,MOTORS_CAR_A3_PIN,DIO_u8LOW);
	DIO_voidSetPinValue(MOTORS_CAR_A4_GROUP,MOTORS_CAR_A4_PIN,DIO_u8LOW);
}
